### ISSUE TITLE
Dev releases have no version info in .info files

### ISSUE THREAD

**Issue by hctom** [drupal-composer/drupal-parse-composer#23]
Currently, when installing dev releases via composer, all version information in the ```.info```files is gone, because the git repo is checked out, but the information is added via Drupal's packaging script when creating the tarball of a release. This is really a problem, when you have modules requiring specific minimum versions of a dependency, but the dependency should be a dev release.

I talked to derhasi about this and we thought it might be useful to be able to install the tarball of a dev release instead of a git checkout... perhaps this may be a flag in the version string during ```composer require "drupal/xyz:>7.1.*TARBALL"```

I'd appreciate your feedback.

Cheers

hctom

**Comment by webflo** [comment]
I had this issue before.

- https://www.drupal.org/project/git_deploy
- Rewrite the requirement and remove the version constraint via hook_system_info_alter because you already know that your dependencies are correct

**Comment by winmillwill** [comment]
> I talked to derhasi about this and we thought it might be useful to be able to install the tarball of a dev release instead of a git checkout... perhaps this may be a flag in the version string during composer require "drupal/xyz:>7.1.*TARBALL"

This code does not run when someone invokes composer, and will never know what flags you pass to composer. Some other project could be undertaken to provide a plugin like this, but it seems wrong because we already have the 'prefer-dist' option, which should do exactly what you seem to want. We provide the wrong dist url for the dev packages right now, which I'm fixing.

There is the separate issue that the Drupal site should work whether or not you use prefer-dist and it works correctly. I don't like the idea of needing caveats to make this work, but if prefer-dist does work correctly, then it's not even our fault; installing with git in any capacity makes this not work. As the git_deploy page mentions, `drush make` handles this, so we should see if we can figure out what happens there and port the functionality to a composer plugin or similar.

**Comment by webflo** [comment]
Closed in favor of #32
